export type Registration = {
  /**
   * If this name is generated by the mocksolaris on search endpoint,
   * find endpoint may generate a different name
   * Do not depend on this name
   */
  name: string;
  registration_number: string;
  /**
   * Only required for companies in Germany
   */
  registration_issuer?: string;
};
